config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  resources :models
  resources :enrollments
  resources :instructors
  resources :courses
  resources :subjects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'subjects#index'
  root 'users#signup'
  get  'course_list',    to: 'courses#index'
  get  'subject_list',    to: 'subjects#index'
  get  'instructor_list',    to: 'instructors#index'
  get  '/signup',  to: 'users#signup'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/my_course',  to: 'sessions#my_course'
  get '/search_course', to: 'courses#search'
  get '/search_courses', to: 'courses#search_courses'
  get '/enroll', to: 'enrollments#enroll'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  def search
  end

  def search_courses
    puts "start searching..."
    @course_list = []
    if !search_params[:course_name].blank? and search_params[:subject_id].blank?
      @course_list = Course.where("course_name LIKE ?","#{search_params[:course_name]}")
    elsif search_params[:course_name].blank? and !search_params[:subject_id].blank?
      @course_list = Course.where(subject_id: search_params[:subject_id])
    elsif !search_params[:course_name].blank? and !search_params[:subject_id].blank?
      list1 = Course.where("course_name LIKE ?", "%#{search_params[:course_name]}%")
      list2 = (Course.where(subject_id: search_params[:subject_id]))
      @course_list = list1 & list2
    end
    puts "course list size: #{@course_list.size}"
    render 'search'
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def search_params
    params
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"><html>
  <head>
    <title>Course</title>
  </head>

  <body>
    <%= render "common/navbar" %>
    <div class="container">
      <table class="table">
        <thead>
          <tr>
            <th>Course code</th>
            <th>Course name</th>
            <th>Course description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @courses.each do |course| %>
            <tr>
              <td><%= course.course_id %></td>
              <td><%= course.course_name %></td>
              <td><%= course.course_description %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </body>
<html>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/courses/search.html.erb
<%
  subjects = []
  all_arr = []
  subjects = Subject.all
  subjects.each do |s|
    single_arr = []
    single_arr << s.subject_name
    single_arr << s.subject_id
    all_arr << single_arr
  end
  puts "total num: #{all_arr.size}"

%>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"><html>
  <head>
    <title>course search</title>
  </head>

  <body>
    <!-- <%= render "common/navbar" %> -->
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <h2>Course search</h2>
      <%= form_tag("/search_courses", method: "get")  do %>
        <%= label_tag(:course_name, "Course name:") %>
        <%= text_field_tag(:course_name) %>
        <%= label_tag(:subject_name, "Subject name:") %>
        <%= select_tag(:subject_id, options_for_select(all_arr)) %>

        <%= submit_tag("Search",class: "btn btn-primary") %>
      <% end %>

      <table class="table">
        <thead>
          <tr>
            <th>Course code</th>
            <th>Course name</th>
            <th>Course description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <%if !@course_list.blank? %>
          <% @course_list.each do |course| %>
            <tr>
              <td><%= course.course_code %></td>
              <td><%= course.course_name %></td>
              <td><%= course.course_description %></td>
              <td><%= link_to 'Enroll', new_enrollment_path(:course_id => course.id) %></td>
            </tr>
          <% end %>
          <% end%>
        </tbody>
      </table>
    </div>
  </body>
<html>